apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  type: ClusterIP ## Default value, not required
  ports:
    - name: "db-service"
      targetPort: 5432
      port: 5432
  selector:
    app: db
