apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 # Port on service object 
      targetPort: 80 # Port on the pod to forward the traffic to
      nodePort: 30008 # Port on each node to expose the service, port range is 30000-32767
  selector:
    app: myapp # label to match for the pods
    type: front-end 