apiVerion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec: # replication controller
  template: # Pod template
    metadata:
      name: myapp-pod #pod name
      labels: # can have any key-value pairs that you want for labels
        app: myapp # will be able to filter label of pods
        type: front-end
      spec: #specification
        containers:
          - name: nginx-container
            image: nginx #Name of the docker image in the docker repository

  replicas: 3
