apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
    - name: "result-service"
      targetPort: 80 # Port of the pod that the service will forward to
      port: 8081 # Port on the service
      nodePort: 31001 # Port on each node to expose the service, port range is 30000-32767
  selector:
    app: result
