apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: "vote-service"
      targetPort: 80 # Port of the pod that the service will forward to
      port: 8080 # Port on the service
      nodePort: 31000 # Port on each node to expose the service, port range is 30000-32767
  selector:
    app: vote
